const API_BASE = "http://127.0.0.1:8000";
const FALLBACK_CENTER = {lat:47.6062,lng:-122.3321};
let currentLocation = null;
let allResources = Array.isArray(window.SAMPLE_RESOURCES) ? window.SAMPLE_RESOURCES : [];
let lastLoadedFrom = "sample";
const $ = s => document.querySelector(s);
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));}
function distanceMiles(a,b){const R=3958.7613,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x));}
function filtered(){const q=( $("#search")?.value||"").toLowerCase().trim(),cat=$("#category")?.value||"Any";return allResources.filter(r=>cat==="Any"||r.category===cat).filter(r=>!q||[r.title,r.description,r.category,r.address,r.eligibility].filter(Boolean).join(" ").toLowerCase().includes(q)).map(r=>({...r,distance_miles:currentLocation&&r.lat&&r.lng?distanceMiles(currentLocation,{lat:+r.lat,lng:+r.lng}):null})).sort((a,b)=>(a.distance_miles??99999)-(b.distance_miles??99999));}
function render(){const out=$("#results");if(!out)return;const list=filtered();out.innerHTML=list.length?list.map(r=>`<article class="resource-card"><div class="card-top"><span class="badge">${esc(r.category||"Community")}</span><span class="trust-badge">${esc(r.verification_state||"source-derived")}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.description||"Community resource")}</p>${r.eligibility?`<p><strong>Who it's for:</strong> ${esc(r.eligibility)}</p>`:""}${r.address?`<p class="meta">📍 ${esc(r.address)}${r.distance_miles!=null?` · ${r.distance_miles.toFixed(1)} mi`:""}</p>`:""}${r.phone?`<p class="meta">☎ ${esc(r.phone)}</p>`:""}${r.hours?`<p class="meta">🕒 ${esc(r.hours)}</p>`:""}${r.collected_at?`<p class="meta">Checked ${new Date(r.collected_at).toLocaleDateString()}</p>`:""}<div class="card-actions">${r.website||r.source_url?`<a href="${esc(r.website||r.source_url)}" target="_blank" rel="noopener">Open source</a>`:""}<button type="button" data-save="${esc(r.id||r.title)}">Save</button>${r.id?`<button type="button" data-report="${esc(r.id)}">Report outdated</button>`:""}</div></article>`).join(""):`<div class="empty-state"><h3>No matches yet</h3><p>Try another category or broader search.</p></div>`;out.querySelectorAll("[data-save]").forEach(b=>b.onclick=()=>{const a=JSON.parse(localStorage.getItem("communityFinderSaved")||"[]"),k=b.dataset.save;if(!a.includes(k))a.push(k);localStorage.setItem("communityFinderSaved",JSON.stringify(a));b.textContent="Saved ✓"});out.querySelectorAll("[data-report]").forEach(b=>b.onclick=()=>alert("Thanks. Production reporting will send this to the review queue."));}
function status(){const e=$("#location-status");if(e)e.textContent=currentLocation?`Using your device location · ${lastLoadedFrom} data`:`Seattle demo area · ${lastLoadedFrom} data`;}
async function loadResources(location=FALLBACK_CENTER){const c=window.COMMUNITY_FINDER_SUPABASE;if(c?.url&&c?.publishableKey){try{const lat=+location.lat,lng=+location.lng,rd=15,dy=rd/69,dx=rd/(69*Math.max(Math.cos(lat*Math.PI/180),.1));const u=`${c.url}/rest/v1/resources?select=*&active=eq.true&latitude=gte.${lat-dy}&latitude=lte.${lat+dy}&longitude=gte.${lng-dx}&longitude=lte.${lng+dx}&limit=200`;const r=await fetch(u,{headers:{apikey:c.publishableKey,Authorization:`Bearer ${c.publishableKey}`},cache:"no-store"});if(!r.ok)throw Error(`Supabase HTTP ${r.status}`);allResources=await r.json();lastLoadedFrom="Supabase";render();status();return;}catch(e){console.warn("Supabase unavailable; using fallback",e);}}try{const p=new URLSearchParams({lat:location.lat,lng:location.lng,radius:15}),r=await fetch(`${API_BASE}/resources?${p}`,{cache:"no-store"});if(!r.ok)throw Error();const d=await r.json();if(Array.isArray(d.resources))allResources=d.resources;lastLoadedFrom="local API";}catch(e){lastLoadedFrom="sample";}render();status();}
function locate(){if(!navigator.geolocation){return;}const s=$("#location-status");if(s)s.textContent="Requesting location…";navigator.geolocation.getCurrentPosition(p=>{currentLocation={lat:p.coords.latitude,lng:p.coords.longitude};loadResources(currentLocation)},()=>{if(s)s.textContent="Location permission wasn't granted. Showing Seattle.";loadResources(FALLBACK_CENTER)},{enableHighAccuracy:false,timeout:10000,maximumAge:300000});}
document.addEventListener("DOMContentLoaded",()=>{ $("#use-location")?.addEventListener("click",locate);["#search","#category","#cost","#time"].forEach(s=>$(s)?.addEventListener("input",render));render();status();if("serviceWorker" in navigator)navigator.serviceWorker.register("./service-worker.js").catch(()=>{});loadResources(FALLBACK_CENTER);});
